language: node_js
node_js:
- '4'
notifications:
  email: false
services:
- mongodb
env:
  global:
  - NODE_ENV: test
addons:
  sauce_connect: true
before_install:
- npm install -g bower@1.3
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
before_script:
- node test/data.js
- grunt minifica
- node server &
- sleep 10
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
- protractor config/protractor.js
before_deploy:
- git config --global user.email 'travis@travis-ci.com'
- git config --global user.name 'Travis CI'
- git checkout $TRAVIS_BRANCH
- git add --all
- git commit -am "Travis commit"
deploy:
  provider: mongodb-atlas
  user: edersonluis.rf@gmail.com
  api_key: u4FjdwmCZQAXS9cXFXrmqqzSnjJaWlAq8HZtZhK1XGS6Bh7AqKpm1zZ4u8ZCUS52
  on:
    repo: edersonlrf/mean-001-cdc-contatooh
