language: node_js
node_js:
- '4'
notifications:
  email: false
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: K5dc/Kyei1aoUpledxuro/51hhC6ECfTn++UV36Hv8U0HVOjvYpit5mDDv/m3ofHN4vHV8PRUDobwugOgE6v4Hbl0S99dgFQDxcJ94LqojUdKAWNvjHMY4YceRe5lz7nFlFIVtZcD47rwzcA+n8Fh9AsRcg6RQHYxU2PRRx83kl6RjzaSX6EYmUMwJHyEjirB3yKGXfFEPFlAPXCwCcKf/ij/thAQuuM7Cle/vttIYse6RuXGxWO1ypf4YWnyUK1cXYP78kuiVUhsXHEp5YOu669L8TX0R9e6H5W1WYuqOGfhz/vAx4DFSzSG2ZGeE1mdlbq2SSRxb+iAK5wIssDZSwoHgXVAYhXjFTsUZsSNh4iB9ZPbD8cHdviV28pI7Jh4bMyw0jJI6+UTjaHDm1iMKgyxMrXGgIq2ewsrN240CYOe3SbvVS51/iGxNEAaADZ1eaofRfsLwGkjqte9XTX1TKfk2uUovVF6IURGyHZiJzKIbzEDamLgnZfHu9Wryeoo2FEFeRmYlt6kEo5att0RwbgdHCwlgL57eNoZx/5c2hXMvajRzWJfOeacBHbZTtROM2UFC/GowCvX4ARq/k9x7lTuODQM2d0fmGEKjRsJgiG5zgOUgLD4eVJXohatNyhr8La8XZqQBGCDYAYRzC4jEPmoKL6uvpv+YdFho1FKsw=
  app: mean-001-cdc-contatooh